### ISSUE TITLE
Mandani Type2 Fuzzy Logic System

### ISSUE THREAD

**Issue by lelivre** [ahmettaskin/type-2-fuzzy-logic-systems-matlab-toolbox#11]
Does the toolbox only support sugeno rule ? Can it support Mamdani rule ?

**Comment by bumieqingyun** [comment]
It cannot support Mamdani rule.

**Comment by bumieqingyun** [comment]
Is there any stuck condition when applying this toolbox?How to solve this problem?

**Comment by ahmettaskin** [comment]
UInfortunately current version only supports Sugeno rule not Mamdani
