### ISSUE TITLE
Spelling mistake.

### ISSUE THREAD

**Issue by ahkhan03** [ahmettaskin/type-2-fuzzy-logic-systems-matlab-toolbox#4]
There seems to be a spelling mistake in initializing uicontrol property. It should be spelled `visible`.

https://github.com/ahmettaskin/type-2-fuzzy-logic-systems-matlab-toolbox/blob/7aaf9bd7272ed47f579ed92763d0a638539511c2/%40ruleEditor/localAddRuleMake.m#L187

**Comment by ahmettaskin** [comment]
Thanks for opening this issue. i have fixed it.
