### ISSUE TITLE
error on view surface

### ISSUE THREAD

**Issue by ameylani** [ahmettaskin/type-2-fuzzy-logic-systems-matlab-toolbox#5]
dear mr. @ahmettaskin ahmet, i have problem i already added the rules and i want to view surface, but there's a warning dialog. even though i already added 8 rules; 2 input with 2 membership function and 2 output with 3 membership function. how can i fix it? so i can get the surfaces.

![1524222051986](https://user-images.githubusercontent.com/38487932/39050351-44bf3d84-44cf-11e8-9881-06200e566d29.jpg)
![1524221475779](https://user-images.githubusercontent.com/38487932/39050353-45e546c2-44cf-11e8-9c26-a515cce0158d.jpg)

**Comment by ahmettaskin** [comment]
Thanks for opening this issue. Our latest release is supporting muıltiple input- single output. Therefore, i have removed adding output button from UI.

**Comment by ameylani** [comment]
I already made 3 input and 1 output, but it still said "index exceeds matrix dimensions" what should i do mr.?
